### ISSUE TITLE
evasys_seminar.evasys_id must not be null.

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [data-quest/EvasysPlugin#56]
Moin, wir kriegen in der 5.1 viele solcher Meldungen ins Error Log:

```
2022/03/03 10:10:51 [error] 3510967#3510967: *6932880 FastCGI sent in stderr: "PHP message: UnexpectedValueException: evasys_seminar.evasys_id must not be null. in /srv/studip_git/lib/models/SimpleORMap.class.php:1846
Stack trace:
#0 /srv/studip_git/public/plugins_packages/data-quest/EvasysPlugin/lib/EvasysSeminar.php(648): SimpleORMap->store()
#1 /srv/studip_git/public/plugins_packages/data-quest/EvasysPlugin/controllers/evaluation.php(50): EvasysSeminar->getSurveyInformation()
#2 /srv/studip_git/vendor/trails/trails.php(557): EvaluationController->show_action()
#3 /srv/studip_git/app/controllers/studip_controller.php(110): Trails_Controller->perform('show')
#4 /srv/studip_git/vendor/trails/trails.php(154): StudipController->perform('show')
#5 /srv/studip_git/vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('evaluation/show')
#6 /srv/studip_git/lib/plugins/core/StudIPPlugin.class.php(166): Trails_Dispatcher->dispatch('evaluation/show')
#7 /srv/studip_git/public/plugins_packages/data-quest/EvasysPlugin/EvasysPlugin.class.php(781): StudIPPlugin->perform('" while reading response header from upstream, client: xxx server: [studip.uni-hannover.de](http://studip.uni-hannover.de/), request: "GET /plugins.php/evasysplugin/evaluation/show?cid=a700a3ec4c640fd8571d8e2c870de2a5 HTTP/2.0", upstream: "[fastcgi://unix:/run/php/php-fpm-studip.sock:](fastcgi://unix/run/php/php-fpm-studip.sock:)", host: "[studip.uni-hannover.de](http://studip.uni-hannover.de/)", referrer: "https://studip.uni-hannover.de/dispatch.php/course/overview?cid=a700a3ec4c640fd8571d8e2c870de2a5"
```

**Comment by Krassmus** [comment]
Ja, Holger hat das schon berichtet. Ich arbeite dran.

**Comment by schuettloeffel-elsa** [comment]
Ah sorry, das hatte ich nicht mitbekommen

**Comment by Krassmus** [comment]
Sollte behoben sein. Falls nicht, bitte wieder öffnen.
