### ISSUE TITLE
Class 'Modules' not found

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [data-quest/EvasysPlugin#66]
Taucht bei uns im Errorlog auf:

```
2022/07/07 10:00:08 [error] 470890#470890: *428788875 FastCGI sent in stderr: "PHP message: Error: Class 'Modules' not found in /srv/studip_git/public/plugins_packages/data-quest/EvasysPlugin/controllers/admin.php:256
Stack trace:
#0 /srv/studip_git/public/plugins_packages/data-quest/EvasysPlugin/controllers/admin.php(26): AdminController->getCourses(Array)
#1 /srv/studip_git/vendor/trails/trails.php(557): AdminController->course_tr_action('efbb65e7192fedb...')
#2 /srv/studip_git/app/controllers/studip_controller.php(110): Trails_Controller->perform('course_tr/efbb6...')
#3 /srv/studip_git/vendor/trails/trails.php(154): StudipController->perform('course_tr/efbb6...')
#4 /srv/studip_git/vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('admin/course_tr...')
#5 /srv/studip_git/lib/plugins/core/StudIPPlugin.class.php(166): Trails_Dispatcher->dispatch('admin/course_tr...')
#6 /srv/studip_git/public/plugins_packages/data-quest/EvasysPlugin/EvasysPlugin.class.php(798): StudIPPlugin->perform('admin/course_tr...')
#7 /srv/studip_git/public/plugins.php(54): Evasys" while reading response header from upstream, client: xxx, server: [studip.uni-hannover.de](http://studip.uni-hannover.de/), request: "GET /plugins.php/evasysplugin/admin/course_tr/efbb65e7192fedbbf2671889624a4e67 HTTP/2.0", upstream: "[fastcgi://unix:/run/php/php-fpm-studip.sock:](fastcgi://unix/run/php/php-fpm-studip.sock:)", host: "[studip.uni-hannover.de](http://studip.uni-hannover.de/)", referrer: "https://studip.uni-hannover.de/dispatch.php/admin/courses/index"
```

**Comment by Krassmus** [comment]
Dieser Fehler kommt, wenn das Evaluationsprofil gespeichert wird und die Zeile im Adminbereich neu geladen wird. Da passt der Quellcode noch nicht zur 5.1 von Stud.IP. Dies ist aber immerhin kein schwerer Fehler, sondern sollte nur die Anzeige betreffen.
